services:
  - type: web
    name: bank-management-backend
    runtime: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: bank-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: bank-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: bank-db
          property: password
      - key: JWT_SECRET
        generateValue: true

    healthCheckPath: /actuator/health

databases:
  - name: bank-db
    databaseName: bankmanagementsystem
    user: bankuser
    plan: free
