services:
  - type: web
    name: bank-management-backend
    runtime: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /actuator/health

    envVars:
      - key: PORT
        value: 8080

      - key: SPRING_PROFILES_ACTIVE
        value: production

      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://dpg-d4cb3j3uibrs738o83lg-a.oregon-postgres.render.com:5432/bankmanagementsystem

      - key: SPRING_DATASOURCE_USERNAME
        value: bankuser

      - key: SPRING_DATASOURCE_PASSWORD
        value: mnaytjVZPSmDw26ZkazKUbKzTDLUlu6f

      - key: JWT_SECRET
        generateValue: true

databases:
  - name: bank-db
    plan: free
    databaseName: bankmanagementsystem
    user: bankuser
