services:
  - type: web
    name: bank-management-backend
    runtime: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile

    envVars:
      - key: PORT
        value: 8080

      - key: DATABASE_URL
        fromDatabase:
          name: bank-db
          property: connectionString

      - key: DB_USERNAME
        fromDatabase:
          name: bank-db
          property: user

      - key: DB_PASSWORD
        fromDatabase:
          name: bank-db
          property: password

      - key: SPRING_PROFILES_ACTIVE
        value: production

      - key: JWT_SECRET
        generateValue: true

    healthCheckPath: /actuator/health

databases:
  - name: bank-db
    databaseName: bankmanagementsystem
    user: bankuser
    plan: free
